### ISSUE TITLE
Demo不能正常使用，求问

### ISSUE THREAD

**Issue by wuyezhu** [pili-engineering/PLDroidCameraStreaming#14]
下面是错误日志：
 threadid=12: calling UncaughtExceptionHandler
FATAL EXCEPTION: TextureMovieEncoder
java.lang.NoSuchMethodError: android.media.MediaCodec.createInputSurface
 	at com.pili.pldroid.streaming.av.video.c.<init>(VideoEncoderCore.java:63)
	at com.pili.pldroid.streaming.av.video.b.a(TextureMovieEncoder.java:303)
	at com.pili.pldroid.streaming.av.video.b.b(TextureMovieEncoder.java:222)
	at com.pili.pldroid.streaming.av.video.b.a(TextureMovieEncoder.java:45)
	at com.pili.pldroid.streaming.av.video.b$b.handleMessage(TextureMovieEncoder.java:386)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
 	at com.pili.pldroid.streaming.av.video.b.run(TextureMovieEncoder.java:206)
	at java.lang.Thread.run(Thread.java:838)

**Comment by jpxiong** [comment]
Android Min API 18, 即 目前 Android 支持的最低版本为 4.3

**Comment by wuyezhu** [comment]
谢谢，果然。
