### ISSUE TITLE
GLSurfaceView 无法在 Fragment 中使用

### ISSUE THREAD

**Issue by daweibayu** [pili-engineering/PLDroidCameraStreaming#158]
我们想把视频上传的业务单独剥离到一个 Fragment，使用的时候发现 render 会有问题，可参见 http://stackoverflow.com/questions/10628998/glsurfaceview-inside-fragment-not-rendering-when-restarted 。
但是我发现 CameraStreamingManager 其实是限定死了，必须要传入 GLSurfaceView，而 GLSurfaceView 相关 render 的代码是混淆过的，所以既没办法自己去渲染 camera prview，也没办法实例化一个你们的 render，期望这里可以给一个解决方案。

**Comment by geeklok** [comment]
你的问题是指通过 backstack 返回时，调用 onResume 无效是么，我们先重现一下这个问题。

**Comment by daweibayu** [comment]
不是返回，相关的 Activity 打开时就会报错。具体的报错信息：
Caused by: java.lang.NullPointerException
at android.opengl.GLSurfaceView.onPause(GLSurfaceView.java:550)
at com.pili.pldroid.streaming.cam.c.a(CameraManager.java:234)
at com.pili.pldroid.streaming.CameraStreamingManager.resume(CameraStreamingManager.java:701)
