### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by nicai1900** [pili-engineering/PLDroidCameraStreaming#80]
Model: M2 Version: Miui v7
 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                            at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
                                                                                            at org.json.JSONTokener.nextValue(JSONTokener.java:94)
                                                                                            at org.json.JSONObject.<init>(JSONObject.java:156)
                                                                                            at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                                            at com.pili.pldroid.streaming.camera.demo.StreamingBaseActivity.onCreate(StreamingBaseActivity.java:112)
                                                                                            at com.pili.pldroid.streaming.camera.demo.HWCodecCameraStreamingActivity.onCreate(HWCodecCameraStreamingActivity.java:55)
                                                                                            at android.app.Activity.performCreate(Activity.java:5939)
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2256)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363) 
                                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5235) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)

**Comment by jpxiong** [comment]
You should pass a valid `Stream` object.
