### ISSUE TITLE
你好 请问demo怎们运行？

### ISSUE THREAD

**Issue by zczcyc0201** [pili-engineering/PLDroidCameraStreaming#81]
你好 请问demo怎们运行？我下载了代码，在androidstudio里运行，点击按钮就崩溃，请问运行之前要做什么设置或操作呢？谢谢

**Comment by zczcyc0201** [comment]
报错如下
 Caused by: java.lang.NullPointerException
            at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
            at org.json.JSONTokener.nextValue(JSONTokener.java:94)
            at org.json.JSONObject.<init>(JSONObject.java:155)
            at org.json.JSONObject.<init>(JSONObject.java:172)
            at com.pili.pldroid.streaming.camera.demo.StreamingBaseActivity.onCreate(StreamingBaseActivity.java:112)
            at com.pili.pldroid.streaming.camera.demo.HWCodecCameraStreamingActivity.onCreate(HWCodecCameraStreamingActivity.java:55)
            at android.app.Activity.performCreate(Activity.java:5249)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
            at android.app.ActivityThread.access$900(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5072)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mianamiana** [comment]
更改Config.DEBUG_MODE 为 false

**Comment by jpxiong** [comment]
使用之前，需要先向 pili@qiniu.com 申请，开通账号之后，可以从 pili streaming cloud 获取 stream json，再把 stream json 传给 sdk 即可。

**Comment by lisnstatic** [comment]
我现在还是得先申请，开通账号才可以用是吗
