### ISSUE TITLE
java.lang.NoClassDefFoundError: com.example.rtmpdemo.CameraStreamingActivity

### ISSUE THREAD

**Issue by ShanZha** [pili-engineering/PLDroidCameraStreaming#9]
请教个问题，我在使用您的PLDroidCameraStreaming时，总提示这个错，是我什么操作有问题吗？

**Comment by jpxiong** [comment]
从标题来看，是这个类没有定义。你检查一下你的类（包括包名），如果仍然有问题，然后贴出点完整的 log

**Comment by ShanZha** [comment]
java.lang.NoClassDefFoundError: com.pili.pldroid.streaming.camera.demo.CameraStreamingActivity
at com.example.rtmpdemo.MainActivity$1.onClick(MainActivity.java:35)
at android.view.View.performClick(View.java:4476)
at android.view.View$PerformClick.run(View.java:18795)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:177)
at android.app.ActivityThread.main(ActivityThread.java:5493)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
at dalvik.system.NativeStart.main(Native Method)


上面是Log，我跟了一下，根本的问题是StreamingBaseActivity这个类找不到，但我已经定义了，所以应该是用您的jar包或so库有问题
Ps：我是Eclipse开发，因此把您的demo进行了移植，不知是否移植问题？

**Comment by jpxiong** [comment]
你好， StreamingBaseActivity 是 demo 里面定义的一个 Activity。

**Comment by jpxiong** [comment]
![image](https://cloud.githubusercontent.com/assets/11766341/8948633/96286ade-35db-11e5-9d94-9da801037414.png)

**Comment by ShanZha** [comment]
哦，那这个意思就只能在demo里用？ 或者说您的jar包和.so文件是根据您的demo包名绑定的？如果是酱紫那我应该怎么使用？谢谢

**Comment by jpxiong** [comment]
Demo 里的代码你可以根据你自己的需求更改。jar 包和 so 文档没有和 demo 包名绑定。

**Comment by ShanZha** [comment]
![Uploading rtmp.png…]()

**Comment by ShanZha** [comment]
那我根据您的demo里的代码修改之后就一直这个错

**Comment by jpxiong** [comment]
可能是因为你的 Activity 是继承的 CameraStreamingActivity，但是你的 demo 里面没有 CameraStreamingActivity 。CameraStreamingActivity 在 sdk 和系统里，并不存在，是需要自己实现的。

**Comment by ShanZha** [comment]
呵呵，肯定不是，那是那样我编译都过不了的，这个错跟jar包是有关系的。您要是方便的话，留个联系方式，交流交流

**Comment by jpxiong** [comment]
你的 activity 是继承的什么？

**Comment by ShanZha** [comment]
跟您的demo一致，即CameraStreamingActivity继承StreamingBaseActivity，其实我就是把您的demo里的代码粘贴过来，唯一的区别是这个demo是我新建的

**Comment by jpxiong** [comment]
那你的 Manifest 里面，有注册么？

**Comment by ShanZha** [comment]
有，要是没有我觉得就正常了

**Comment by jpxiong** [comment]
你把 Manifest 里面的 StreamingBaseActivity 声明给去掉试试...

**Comment by jpxiong** [comment]
另外，能否将 CameraStreamingActivity 所属的包名发来看看，总感觉是 CameraStreamingActivity 这个类有问题。修改之后，记得 clear 一下工程。

**Comment by ShanZha** [comment]
我邮箱是xingrjing@sina.com,您给我发个邮件，然后我从邮箱里给你我的相关代码，帮我看看

**Comment by jpxiong** [comment]
已发～请查收

**Comment by jpxiong** [comment]
导入到 Android studio 里面报如下错误，这个是正常的报错，因为我发现你的 stream json string 并没有配置。所以，我不确定是不是 eclipse 哪个地方配置有问题...或者你是否尝试 clear/rebuild project? 不管怎么样，个人建议如果开发 android app，慢慢地转向 android studio，因为 google 都计划不支持 eclipse adt 了。可以确认的是提供的 sdk 应该是没有问题的。请知晓。
```
07-30 04:32:38.472  27158-27158/com.example.rtmpdemo D/AndroidRuntime﹕ Shutting down VM
07-30 04:32:38.473  27158-27158/com.example.rtmpdemo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.rtmpdemo, PID: 27158
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.rtmpdemo/com.pili.pldroid.streaming.camera.demo.CameraStreamingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.getString(java.lang.String)' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.access$800(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5258)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.getString(java.lang.String)' on a null object reference
            at com.pili.pldroid.streaming.StreamingProfile$Stream.<init>(StreamingProfile.java:194)
            at com.pili.pldroid.streaming.camera.demo.CameraStreamingActivity.onCreate(CameraStreamingActivity.java:42)
            at android.app.Activity.performCreate(Activity.java:5979)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2262)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.access$800(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5258)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by jpxiong** [comment]
你也可以尝试重新依赖 jar 包，确认 jar 确实是正确依赖了的：
Java build path-> Libraries -> Add External JARS..

**Comment by ShanZha** [comment]
好，非常感谢您这两天的回复
